import { BrandProfile } from "@/types/brand";

export const brandProfiles: Record<string, BrandProfile> = {
  "canon-official": {
    slug: "canon-official",
    name: "Canon Official",
    description: "Official Canon camera and equipment rental service. We provide professional grade cameras and lenses for photography and videography needs.",
    location: "Jakarta Selatan",
    address: "Jl. Jendral Sudirman No. 10, Jakarta Selatan, DKI Jakarta 12190",
    phone: "+62 21 555 0123",
    email: "rental@canonofficial.id",
    website: "https://canonofficial.id",
    coverImage: "/placeholder-cover.jpg",
    logoInitial: "C",
    rating: 4.8,
    reviewCount: 243,
    establishedYear: 2015,
    type: "rental",
    socialMedia: {
      facebook: "canonofficialid",
      instagram: "@canonofficial.id",
    },
    operatingHours: {
      weekday: "08:00 - 20:00",
      weekend: "09:00 - 18:00",
    },
    items: [
      {
        id: "1",
        name: "Canon EOS R5 Body Only",
        description: "Professional mirrorless camera with 45MP sensor and 8K video recording capability.",
        features: ["45MP Full-Frame", "8K Video", "Dual Card Slots"],
        price: 750000,
        priceUnit: "hari",
        image: "/placeholder-camera.jpg",
        type: "equipment",
      },
      {
        id: "2",
        name: "Canon RF 24-70mm f/2.8L",
        description: "Professional standard zoom lens with constant f/2.8 aperture.",
        features: ["24-70mm Range", "f/2.8 Aperture", "Weather Sealed"],
        price: 450000,
        priceUnit: "hari",
        image: "/placeholder-lens.jpg",
        type: "equipment",
      },
    ],
  },
  "masjid-al": {
    slug: "masjid-al",
    name: "Masjid Al",
    description: "Established in 1998, Masjid Al serves as a community hub providing not just spiritual guidance but also various facilities that are available for community events, seminars, and gatherings. Our beautiful architectural details from rentals go towards mosque operational and charity.",
    location: "Jakarta Selatan",
    address: "Jl. Jendral Sudirman No. 10, Jakarta Selatan, DKI Jakarta 12190",
    phone: "+62 21 555 0123",
    email: "admin@masjidalid.org",
    coverImage: "/placeholder-mosque.jpg",
    logoInitial: "🌙",
    rating: 4.8,
    reviewCount: 150,
    establishedYear: 1998,
    type: "venue",
    socialMedia: {
      facebook: "masjidalid",
      instagram: "@masjid.al",
    },
    operatingHours: {
      weekday: "08:00 - 17:00",
    },
    items: [
      {
        id: "1",
        name: "Main Hall (Aula Utama)",
        description: "Spacious hall suitable for weddings, seminars, and large gatherings up to 800 people with AC included.",
        capacity: "800 Pax",
        size: "AC Included",
        features: ["800 Pax", "AC Included"],
        price: 2500000,
        priceUnit: "event",
        image: "/placeholder-hall.jpg",
        type: "venue",
      },
      {
        id: "2",
        name: "Meeting Room Al-Fatih",
        description: "Intimate meeting space perfect for board meetings or small workshops up to 30 people with Projector.",
        capacity: "30 Pax",
        size: "Projector",
        features: ["30 Pax", "Projector"],
        price: 500000,
        priceUnit: "hour",
        image: "/placeholder-meeting.jpg",
        type: "venue",
      },
      {
        id: "3",
        name: "Full Sound System Set",
        description: "Complete audio solution including 4 active speakers, mixer, and wireless microphones.",
        features: ["4 Mics", "With Mixer"],
        price: 1200000,
        priceUnit: "day",
        image: "/placeholder-sound.jpg",
        type: "equipment",
      },
      {
        id: "4",
        name: "Event Chairs (Futura)",
        description: "Standard comfortable chairs with optional covers (white/various).",
        features: ["Min. 100pcs", "Custom Covers"],
        price: 15000,
        priceUnit: "day",
        image: "/placeholder-chairs.jpg",
        type: "equipment",
      },
    ],
  },
  "sony-id": {
    slug: "sony-id",
    name: "Sony ID",
    description: "Official Sony camera and equipment rental service in Indonesia. Professional equipment for your creative needs.",
    location: "Bandung",
    address: "Jl. Asia Afrika No. 8, Bandung, Jawa Barat 40111",
    phone: "+62 22 555 0456",
    email: "rental@sonyid.co.id",
    coverImage: "/placeholder-cover.jpg",
    logoInitial: "S",
    rating: 4.9,
    reviewCount: 189,
    establishedYear: 2012,
    type: "rental",
    operatingHours: {
      weekday: "09:00 - 19:00",
      weekend: "10:00 - 16:00",
    },
    items: [
      {
        id: "1",
        name: "Sony Alpha A7 III Kit Lens",
        description: "Full-frame mirrorless camera with excellent low-light performance.",
        features: ["24MP Full-Frame", "4K Video", "5-axis Stabilization"],
        price: 450000,
        priceUnit: "hari",
        image: "/placeholder-camera.jpg",
        type: "equipment",
      },
    ],
  },
  "dji-store": {
    slug: "dji-store",
    name: "DJI Store",
    description: "Official DJI drone and gimbal rental service. Professional aerial and stabilization equipment.",
    location: "Jakarta Barat",
    address: "Jl. Tanjung Duren No. 15, Jakarta Barat, DKI Jakarta 11470",
    phone: "+62 21 555 0789",
    email: "rental@djistore.id",
    coverImage: "/placeholder-cover.jpg",
    logoInitial: "D",
    rating: 5.0,
    reviewCount: 156,
    establishedYear: 2018,
    type: "rental",
    operatingHours: {
      weekday: "10:00 - 20:00",
    },
    items: [
      {
        id: "1",
        name: "DJI Mavic 3 Cine Premium",
        description: "Professional drone with Hasselblad camera and ProRes recording.",
        features: ["Hasselblad Camera", "ProRes 422 HQ", "46min Flight Time"],
        price: 1200000,
        priceUnit: "hari",
        image: "/placeholder-drone.jpg",
        type: "equipment",
      },
    ],
  },
};

export const getBrandBySlug = (slug: string): BrandProfile | null => {
  return brandProfiles[slug] || null;
};
