import { Product } from "@/types/explore";

export const dummyProducts: Product[] = [
  {
    id: "1",
    name: "Canon EOS R5 Body Only",
    brand: "Canon Official",
    category: "Kamera",
    type: "barang",
    location: "Jakarta Selatan",
    price: 750000,
    priceUnit: "hari",
    image: "/placeholder-camera.jpg",
    rating: 4.8,
    reviewCount: 243,
    availability: "available",
    tags: ["Terjual", "Populer"],
  },
  {
    id: "2",
    name: "Sony Alpha A7 III Kit Lens",
    brand: "Sony ID",
    category: "Kamera",
    type: "barang",
    location: "Bandung",
    price: 450000,
    priceUnit: "hari",
    image: "/placeholder-camera.jpg",
    rating: 4.9,
    reviewCount: 189,
    availability: "available",
    tags: ["Sisa Sedikit"],
  },
  {
    id: "3",
    name: "DJI Mavic 3 Cine Premium",
    brand: "DJI Store",
    category: "Drone",
    type: "barang",
    location: "Jakarta Barat",
    price: 1200000,
    priceUnit: "hari",
    image: "/placeholder-drone.jpg",
    rating: 5.0,
    reviewCount: 156,
    availability: "available",
    tags: ["Tersedia"],
  },
  {
    id: "4",
    name: "MacBook Pro M1 Max 16\"",
    brand: "iBox Rentals",
    category: "Laptop",
    type: "barang",
    location: "Bandung",
    price: 900000,
    priceUnit: "hari",
    image: "/placeholder-laptop.jpg",
    rating: 4.7,
    reviewCount: 98,
    availability: "rented",
    tags: ["Disewa"],
  },
  {
    id: "5",
    name: "Godox SL60W Video Light",
    brand: "Studio Center",
    category: "Lighting",
    type: "barang",
    location: "Jakarta Selatan",
    price: 150000,
    priceUnit: "hari",
    image: "/placeholder-light.jpg",
    rating: 4.6,
    reviewCount: 234,
    availability: "available",
    tags: ["Tersedia"],
  },
  {
    id: "6",
    name: "Rode Wireless Go II Dual",
    brand: "Audiogear",
    category: "Audio",
    type: "barang",
    location: "Bandung",
    price: 200000,
    priceUnit: "hari",
    image: "/placeholder-mic.jpg",
    rating: 4.9,
    reviewCount: 167,
    availability: "available",
    tags: ["Tersedia"],
  },
  {
    id: "7",
    name: "Studio Foto Professional",
    brand: "PhotoSpace Studio",
    category: "Studio Foto",
    type: "tempat",
    location: "Jakarta Pusat",
    price: 500000,
    priceUnit: "jam",
    image: "/placeholder-studio.jpg",
    rating: 4.8,
    reviewCount: 312,
    availability: "available",
    tags: ["Populer"],
  },
  {
    id: "8",
    name: "Coworking Space Premium",
    brand: "WorkHub",
    category: "Coworking Space",
    type: "tempat",
    location: "Jakarta Selatan",
    price: 100000,
    priceUnit: "jam",
    image: "/placeholder-coworking.jpg",
    rating: 4.7,
    reviewCount: 445,
    availability: "available",
    tags: ["Tersedia"],
  },
  {
    id: "9",
    name: "Meeting Room Kapasitas 10",
    brand: "MeetSpace",
    category: "Meeting Room",
    type: "tempat",
    location: "Bandung",
    price: 250000,
    priceUnit: "jam",
    image: "/placeholder-meeting.jpg",
    rating: 4.5,
    reviewCount: 89,
    availability: "available",
    tags: ["Tersedia"],
  },
  {
    id: "10",
    name: "GoPro Hero 11 Black",
    brand: "GoPro Indonesia",
    category: "Action Camera",
    type: "barang",
    location: "Jakarta Barat",
    price: 300000,
    priceUnit: "hari",
    image: "/placeholder-gopro.jpg",
    rating: 4.8,
    reviewCount: 276,
    availability: "available",
    tags: ["Populer"],
  },
  {
    id: "11",
    name: "Gimbal DJI RS3 Pro",
    brand: "DJI Store",
    category: "Gimbal",
    type: "barang",
    location: "Jakarta Selatan",
    price: 350000,
    priceUnit: "hari",
    image: "/placeholder-gimbal.jpg",
    rating: 4.9,
    reviewCount: 198,
    availability: "available",
    tags: ["Tersedia"],
  },
  {
    id: "12",
    name: "Event Hall 200 Orang",
    brand: "Grand Hall",
    category: "Event Space",
    type: "tempat",
    location: "Jakarta Pusat",
    price: 2000000,
    priceUnit: "hari",
    image: "/placeholder-hall.jpg",
    rating: 4.6,
    reviewCount: 134,
    availability: "available",
    tags: ["Premium"],
  },
];

export const brands = [
  "Canon Official",
  "Sony ID",
  "DJI Store",
  "iBox Rentals",
  "Studio Center",
  "Audiogear",
  "PhotoSpace Studio",
  "WorkHub",
  "MeetSpace",
  "GoPro Indonesia",
  "Grand Hall",
];

export const categories = [
  "Kamera",
  "Drone",
  "Laptop",
  "Lighting",
  "Audio",
  "Studio Foto",
  "Coworking Space",
  "Meeting Room",
  "Action Camera",
  "Gimbal",
  "Event Space",
];

export const locations = [
  "Jakarta Selatan",
  "Jakarta Barat",
  "Jakarta Pusat",
  "Bandung",
];
