import { ProductDetail } from "@/types/product-detail";

export const productDetails: Record<string, ProductDetail> = {
  "1": {
    id: "1",
    name: "Main Hall (Aula Utama)",
    type: "tempat",
    brand: "Masjid Al",
    brandSlug: "masjid-al",
    brandLogo: "🌙",
    category: "Aula",
    location: "Jakarta Selatan",
    rating: 4.8,
    reviewCount: 127,
    price: 2500000,
    priceUnit: "event",
    images: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    description:
      "Aula serbaguna Masjid Al menawarkan ruang luas dan elegan untuk berbagai acara Anda. Dengan arsitektur modern yang memukau, tempat ini cocok untuk event korporat, pernikahan, seminar, dan gathering. Dilengkapi dengan fasilitas lengkap dan sistem audio visual berkualitas tinggi untuk menunjang acara Anda.\n\nDilengkapi dengan fasilitas modern seperti AC, sistem pencahayaan canggih, sound system yang mumpuni, serta area parkir yang luas. Kapasitas hingga 800 orang dalam satu waktu membuat tempat ini ideal untuk acara skala menengah hingga besar.",
    facilities: [
      { icon: "users", label: "Kapasitas", value: "Hingga 800 orang" },
      { icon: "wind", label: "Full AC", value: "Pendingin sentral" },
      { icon: "music", label: "Sound System", value: "Paket standar" },
      { icon: "car", label: "Parkir Luas", value: "50 mobil / 100 motor" },
    ],
    specifications: [
      { label: "Luas Area", value: "600 m²" },
      { label: "Tinggi Plafon", value: "7 meter" },
      { label: "Kapasitas Maksimal", value: "800 orang" },
      { label: "Jam Operasional", value: "08.00 - 17.00 WIB" },
    ],
    owner: {
      name: "Masjid Al",
      avatar: "🌙",
      location: "Jakarta Selatan",
      memberSince: "Sejak 1998",
      verified: true,
    },
    reviews: [
      {
        id: "1",
        userName: "Ani Amalia",
        userAvatar: "AA",
        rating: 5,
        date: "3 hari yang lalu",
        comment:
          "Tempatnya sangat bagus! Aula sangat bersih dan design. Fasilitas sangat lengkap dan harganya sangat worth it!",
      },
      {
        id: "2",
        userName: "Budi Santoso",
        userAvatar: "BS",
        rating: 4,
        date: "1 minggu lalu",
        comment:
          "Overall bagus, petugas sangat ramah dan helpful. Hanya saja akses jalan agak sempit tapi gak panjang banget kok.",
      },
    ],
    relatedProducts: [
      {
        id: "2",
        name: "Meeting Room Al-Fatih",
        image: "/api/placeholder/400/400",
        rating: 4.9,
        price: 500000,
        priceUnit: "jam",
        location: "Jakarta Selatan",
      },
      {
        id: "3",
        name: "Full Sound System Set",
        image: "/api/placeholder/400/400",
        rating: 4.7,
        price: 350000,
        priceUnit: "hari",
        location: "Jakarta Selatan",
      },
      {
        id: "related-3",
        name: "Aula Griya Modern",
        image: "/api/placeholder/400/400",
        rating: 4.8,
        price: 2000000,
        priceUnit: "event",
        location: "Sidoarjo",
      },
      {
        id: "related-4",
        name: "Pendopo Agung",
        image: "/api/placeholder/400/400",
        rating: 4.9,
        price: 3500000,
        priceUnit: "event",
        location: "Surabaya",
      },
    ],
  },
  "2": {
    id: "2",
    name: "Meeting Room Al-Fatih",
    type: "tempat",
    brand: "Masjid Al",
    brandSlug: "masjid-al",
    brandLogo: "🌙",
    category: "Meeting Room",
    location: "Jakarta Selatan",
    rating: 4.9,
    reviewCount: 85,
    price: 500000,
    priceUnit: "jam",
    images: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    description:
      "Meeting Room Al-Fatih adalah ruang pertemuan yang dirancang khusus untuk keperluan bisnis dan profesional. Dengan desain modern dan fasilitas lengkap, ruangan ini sempurna untuk rapat, workshop, pelatihan, atau diskusi kelompok kecil.\n\nDilengkapi dengan proyektor HD, whiteboard besar, koneksi internet berkecepatan tinggi, serta AC yang nyaman. Kapasitas ideal untuk 20-30 orang dengan suasana tenang dan kondusif.",
    facilities: [
      { icon: "users", label: "Kapasitas", value: "20-30 orang" },
      { icon: "wind", label: "AC", value: "Split 2 unit" },
      { icon: "monitor", label: "Projector", value: "HD Ready + Screen" },
      { icon: "wifi", label: "WiFi", value: "High Speed 100 Mbps" },
    ],
    specifications: [
      { label: "Luas Area", value: "50 m²" },
      { label: "Setup", value: "Theater / Classroom" },
      { label: "Kapasitas Maksimal", value: "30 orang" },
      { label: "Jam Operasional", value: "08.00 - 17.00 WIB" },
    ],
    owner: {
      name: "Masjid Al",
      avatar: "🌙",
      location: "Jakarta Selatan",
      memberSince: "Sejak 1998",
      verified: true,
    },
    reviews: [
      {
        id: "1",
        userName: "Dewi Kusuma",
        userAvatar: "DK",
        rating: 5,
        date: "1 minggu lalu",
        comment:
          "Ruangan sangat nyaman dan bersih. Proyektornya jernih dan WiFi cepat. Cocok banget untuk meeting kantor!",
      },
      {
        id: "2",
        userName: "Ahmad Fauzi",
        userAvatar: "AF",
        rating: 5,
        date: "2 minggu lalu",
        comment:
          "Lokasi strategis, fasilitas lengkap, harga terjangkau. Recommended!",
      },
    ],
    relatedProducts: [
      {
        id: "1",
        name: "Main Hall (Aula Utama)",
        image: "/api/placeholder/400/400",
        rating: 4.8,
        price: 2500000,
        priceUnit: "event",
        location: "Jakarta Selatan",
      },
      {
        id: "3",
        name: "Full Sound System Set",
        image: "/api/placeholder/400/400",
        rating: 4.7,
        price: 350000,
        priceUnit: "hari",
        location: "Jakarta Selatan",
      },
      {
        id: "related-3",
        name: "Aula Griya Modern",
        image: "/api/placeholder/400/400",
        rating: 4.8,
        price: 2000000,
        priceUnit: "event",
        location: "Sidoarjo",
      },
      {
        id: "related-4",
        name: "Studio Foto Profesional",
        image: "/api/placeholder/400/400",
        rating: 4.9,
        price: 750000,
        priceUnit: "jam",
        location: "Jakarta Pusat",
      },
    ],
  },
  "3": {
    id: "3",
    name: "Full Sound System Set",
    type: "barang",
    brand: "Masjid Al",
    brandSlug: "masjid-al",
    brandLogo: "🌙",
    category: "Audio Equipment",
    location: "Jakarta Selatan",
    rating: 4.7,
    reviewCount: 63,
    price: 350000,
    priceUnit: "hari",
    images: [
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
      "/api/placeholder/800/600",
    ],
    description:
      "Paket sound system profesional yang cocok untuk berbagai jenis acara seperti seminar, workshop, pernikahan, atau gathering. Sistem audio berkualitas tinggi dengan operator berpengalaman.\n\nPaket ini sudah termasuk 4 speaker aktif, mixer digital, 4 microphone wireless, kabel lengkap, dan teknisi yang akan membantu setup dan operate selama acara berlangsung.",
    facilities: [
      { icon: "music", label: "Speaker", value: "4 Active Speaker 500W" },
      { icon: "mic", label: "Microphone", value: "4 Wireless Mic" },
      { icon: "settings", label: "Mixer", value: "Digital Mixer 16 Channel" },
      { icon: "user", label: "Operator", value: "Teknisi berpengalaman" },
    ],
    specifications: [
      { label: "Daya Output", value: "2000W Total" },
      { label: "Coverage Area", value: "Hingga 500 orang" },
      { label: "Setup Time", value: "1-2 jam" },
      { label: "Durasi Rental", value: "Minimal 1 hari (8 jam)" },
    ],
    owner: {
      name: "Masjid Al",
      avatar: "🌙",
      location: "Jakarta Selatan",
      memberSince: "Sejak 1998",
      verified: true,
    },
    reviews: [
      {
        id: "1",
        userName: "Rina Safitri",
        userAvatar: "RS",
        rating: 5,
        date: "5 hari lalu",
        comment:
          "Sound systemnya bagus banget, suaranya jernih. Operatornya juga sangat membantu dan profesional!",
      },
      {
        id: "2",
        userName: "Budi Hartono",
        userAvatar: "BH",
        rating: 4,
        date: "2 minggu lalu",
        comment:
          "Kualitas sound oke, harga kompetitif. Cuma setup agak lama sedikit tapi overall bagus.",
      },
    ],
    relatedProducts: [
      {
        id: "1",
        name: "Main Hall (Aula Utama)",
        image: "/api/placeholder/400/400",
        rating: 4.8,
        price: 2500000,
        priceUnit: "event",
        location: "Jakarta Selatan",
      },
      {
        id: "2",
        name: "Meeting Room Al-Fatih",
        image: "/api/placeholder/400/400",
        rating: 4.9,
        price: 500000,
        priceUnit: "jam",
        location: "Jakarta Selatan",
      },
      {
        id: "related-1",
        name: "Paket Lighting Professional",
        image: "/api/placeholder/400/400",
        rating: 4.8,
        price: 450000,
        priceUnit: "hari",
        location: "Jakarta Selatan",
      },
      {
        id: "related-2",
        name: "Projector + Screen",
        image: "/api/placeholder/400/400",
        rating: 4.7,
        price: 250000,
        priceUnit: "hari",
        location: "Jakarta Selatan",
      },
    ],
  },
};

export function getProductDetail(id: string): ProductDetail | undefined {
  return productDetails[id];
}
